---
swagger: "2.0"
info:
  version: "1.0.0"
  title: "Taskcluster service"
consumes:
  - application/json
produces:
  - application/json
paths:

  /:

    get:
      operationId: "shipit_taskcluster.api.list_steps"
      description: List all Taskcluster steps with status
      responses:
        200:
          description: List of all steps

  /{uid}/definition:

    get:
      operationId: "shipit_taskcluster.api.get_step"
      description: Step definition
      parameters:
          - $ref: '#/parameters/uid'
      responses:
        200:
          description: Definition of a Taskcluster step
          schema:
            $ref: '#/definitions/Step'


  /{uid}/status:

    get:
      operationId: "shipit_taskcluster.api.get_step_status"
      description: Status of a Taskcluster step
      parameters:
        - $ref: "#/parameters/uid"
      responses:
        200:
          description: Status of a Taskcluster step
          schema:
            $ref: '#/definitions/StepResult'

  /{uid}:
    put:
      operationId: "shipit_taskcluster.api.create_step"
      description: Create new Taskcluster step
      parameters:
        - $ref: "#/parameters/uid"
      responses:
        200:
          description: Returns nothing

    delete:
      operationId: "shipit_taskcluster.api.delete_step"
      description: Remove a Taskcluster step
      parameters:
        - $ref: '#/parameters/uid'
      responses:
        200:
          description: Removal of Taskcluster step

  # taskcluster specific
  /{uid}/cancel:
    put:
      operationId: "shipit_taskcluster.api.cancel_task_group"
      description: ""
      parameters:
        - $ref: '#/parameters/uid'
      responses:
        200:
          description: Taskcluster task cancel task group

  /{uid}/tasks/{taskId}/cancel:
    put:
      operationId: "shipit_taskcluster.api.cancel_single_task"
      description: ""
      parameters:
        - $ref: '#/parameters/uid'
        - $ref: '#/parameters/taskId'
      responses:
        200:
          description: Taskcluster task cancelled

  /{uid}/tasks/{taskId}/rerun:
    put:
      operationId: "shipit_taskcluster.api.rerun_task"
      description: "Reruns a Taskcluster step. This forces a new run num even if max is reached"
      parameters:
        - $ref: '#/parameters/uid'
        - $ref: '#/parameters/taskId'
      responses:
        200:
          description: Taskcluster task rerun

  /{uid}/tasks/{taskId}/report-completed:
    put:
      operationId: "shipit_taskcluster.api.report_task_complete"
      description: ""
      parameters:
        - $ref: '#/parameters/uid'
        - $ref: '#/parameters/taskId'
      responses:
        200:
          description: Taskcluster task reported complete


definitions:

  # Step and StepResult definitions seem generic enough that they should be defined in a more global
  # location for all shipit services that represent a step
  StepResult:
    type: object
    required:
      - state
    properties:
      state:
        type: string
        enum:
          - starting # / pending
          - running
          - stopping
          - exception
          - completed #/ success
          - failed
      message:
        type: string
        description: More elaborate description of state for humans.
      output:
        $ref: '#/definitions/Output'

  Step:
    type: object
    required:
      - uid
      - input
      - parameters
    properties:
      uid:
        type: string
      input:
        $ref: '#/definitions/Input'
      parameters:
        $ref: '#/definitions/Parameters'

  Parameters:
    type: object

  Input:
    type: object

  Output:
    type: object

parameters:
    uid:
        name: uid
        in: path
        description: Step UID
        required: true
        type: string
    taskId:
      name: taskId
      in: path
      description: Identifier for a Taskcluster task
      required: true
      type: string
